version: '3.8'
services:
  db_stats:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stat_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  db_main:
    image: postgres:13.7-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  main_server:
    build: ./main_server
    ports:
      - "8080:8080"
    depends_on:
      - stats_server
    environment:
      - SERVER_PORT=8080
      - STATS_SERVER_URL=http://stats_server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_main:5432/ewm_main_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats_server:
    build: ./stats_server
    ports:
      - "9090:9090"
    depends_on:
      - db_stats
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_stats:5432/ewm_stat_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
