DROP TABLE IF EXISTS category_event CASCADE;
DROP TABLE IF EXISTS request_moderation CASCADE;
DROP TABLE IF EXISTS compilation CASCADE;
DROP TABLE IF EXISTS compilation_event CASCADE;
DROP TABLE IF EXISTS request_event CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE category_event (
    category_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(64) UNIQUE NOT NULL,
    CONSTRAINT pk_category_event PRIMARY KEY (category_id)
);

CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(256) NOT NULL,
    email VARCHAR(256) UNIQUE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(512) NOT NULL,
    category_id INT NOT NULL,
    initiator_id INT NOT NULL,
    location_latitude FLOAT(24) NOT NULL,
    location_longitude FLOAT(24) NOT NULL,
    title VARCHAR(512) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    description VARCHAR(1000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    published_on TIMESTAMP,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR(64) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_events PRIMARY KEY (event_id),
    FOREIGN KEY (category_id) REFERENCES category_event (category_id) ON DELETE CASCADE,
    FOREIGN KEY (initiator_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE request_event (
    request_event_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id INT NOT NULL,
    created TIMESTAMP NOT NULL,
    requester INT NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_request_event PRIMARY KEY (request_event_id),
    FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE CASCADE,
    FOREIGN KEY (requester) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE request_moderation (
    request_moderation_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id INT NOT NULL,
    description VARCHAR(1000) NOT NULL,
    request_date TIMESTAMP NOT NULL,
    CONSTRAINT pk_request_moderation PRIMARY KEY (request_moderation_id),
    FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE CASCADE
);

CREATE TABLE compilation (
    compilation_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(512) NOT NULL,
    pinned BOOLEAN NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);

CREATE TABLE compilation_event (
    event_id INT NOT NULL,
    compilation_id INT NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE CASCADE,
    FOREIGN KEY (compilation_id) REFERENCES compilation (compilation_id) ON DELETE CASCADE
);




